package com.example.EmployeeManagement.model;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

@Entity // To mark this class as a JPA entity (a database table)
public class Employee {

    @Id //  Marks 'id' as the Primary Key for Entity in DB
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configure ID to be auto-generated by the DB
    private int id;

    @NotBlank(message = "Name is Required!") // Input Validation Not Blank
    private String name;

    @Min(value = 18, message = "Employee must be at least 18 years old") // Input Validation Min Age
    private int age;

    // Default Constructor
    public Employee(){

    }
    // Paramaterized Constructor
    public Employee(int id, String name, int age){
        this.name = name;
        this.age = age;
        this.id = id;
    }
    // Getters
    public String getName(){
        return name;
    }
    public int getId(){
        return id;
    }
    public int getAge(){
        return age;
    }
    // Setters
    public void setId(int id){
        this.id = id;
    }
    public void setAge(int age){
        this.age = age;
    }
    public void setName(String name){
        this.name = name;
    }
    // toString
    @Override
    public String toString(){
        return id + " " + name + " " + age;
    }

}
